### PR TITLE
Feature/eraser feature

### LINKED ISSUE #6: [FEATURE] - Implement an eraser tool in the toolbar
# Feature Request

- [x] I agree to follow this project's Contributing Guidelines.

## Proposed Solution

Implement an eraser tool in the toolbar on the room page to allow users to clean a particular part of the board.

## Implementation Steps:
1.  Refer to the roughjs API doccumentation - https://github.com/rough-stuff/rough/wiki
2.  Follow the coding style used to implement other tools and structure your jsx accordingly
3.  Implement inside a seperate div inside toolbar seperate from the drawing tools.
4.  Go through the entire implementation process of other tools both frontend and the connection with socket io carefully.
5.  Add the frontend implementation.
6.   Connect with backend using event emmitor of socket.io on server.js file
7.  Test your changes and push to github

**Expected Outcome:**
 A eraser tool Should be there inside the tool bar

### PR DESCRIPTION
**Pull request by JavidSumra**
# Title and Issue number 

Title : Implement an Eraser Tool in the Toolbar

Issue No. : #6 

Close #6 

# Video/Screenshots (mandatory)

https://github.com/sd012gfhkhhvh/Slate.AI/assets/112365664/22a5fb1a-2359-4362-ba16-c7ead7d5bbe4

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
**Overview:**
This enhancement introduces a dynamic eraser size feature to the toolbar, providing users with greater flexibility and control over their eraser tool in the application. The initial implementation sets the eraser size to a fixed value of 20.

**Details:**
The current state of the application's toolbar lacks the ability to adjust the eraser size, making the eraser tool less versatile for users with specific precision requirements. This enhancement addresses this limitation by incorporating a dynamic eraser size feature.

**Key Changes:**
1. **Default Eraser Size:**
   - The initial default eraser size is set to 20 for consistency with the previous version.

2. **Backend Implementation:**
   - The backend logic is updated to handle Erase.

**Note:** The fixed initial eraser size of 20 is subject to change based on community feedback and consensus.

***Are you contributing under any Open-source programme?***
I am Contributing Under JWOC 2024

### CODE REVIEW

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra saw your changes. It's a pretty good one. But there is 2 small issues-
1. the eraser only works onMouseUp event, I need to click the mouse to erase which is not an ideal thing to do. 
2. The changes are not propageting to the other room members board.
can you do something about them?

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh can you please provide me with a Preview Approval.

**Comment by JavidSumra** [comment]
Hello @sd012gfhkhhvh, the modifications are now spreading to the boards of other members in the room. Additionally, you can now erase content by dragging the cursor.

https://github.com/sd012gfhkhhvh/Slate.AI/assets/112365664/81b00fc4-f432-4fed-8d2c-8ffed7f8084a

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra  Bro you are going great, But the changes are still not propageting to the other members. 
I am giving u a clue - 
There is a small mistake made inside the whiteboard component, Its a one liner mistake. Let me know if You got it.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh for me on the local server it works fine so can you please share with me a video so I can understand the exact issue.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh please Add `JWOC` and `Hard` Tag To This PR Please Mentor.

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh please Add `JWOC` and `Hard` Tag To This PR Please Mentor.
> 

Dont worry I will.

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh for me on the local server it works fine so can you please share with me a video so I can understand the exact issue. 

I tested your changes locally, it worked fine there but in the production the eraser is not propagated to other room members.

I would suggest you to not use getelementbyId("canvas") at the top under use effect, instade use canvas = canvasref.current. 

Try it once and let me know.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh I'll let you know by tonight.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Now I Made Some Necessary Changes Please Checkout My PR.

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh Now I Made Some Necessary Changes Please Checkout My PR.

saw your changes but it's sitll not working in the production. For now do one thing just remove the comment at line 68 in the whiteboard component. I will marge your pr after the issue#1 get resolved because You just need to change the classnames of your eraser componets. I will let you know after it get resolved. Till then try to deploy your code and let me know if you have got any fixes in the production.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir Can You Please Share Any Video of the Deployment Issue or Access to the Deployment App?

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh  It seems like you may need to update the backend service on Render. I recommend redeploying the backend service, as this should resolve the issue.

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh  It seems like you may need to update the backend service on Render. I recommend redeploying the backend service, as this should resolve the issue.

Yeah, i also think so. Vercel autoupdates the changes in a pr but render does not.

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh so what should I need to do now?

**Comment by sd012gfhkhhvh** [comment]
> Hey @sd012gfhkhhvh so what should I need to do now? 

Wait untill issue#1 get resolved. You jist need to marge the changes and implement taiwind classes instade of bootstrap in your eraser div.

**Comment by sd012gfhkhhvh** [comment]
issue #6 resolved and sucsessfully merged into dev

**Pull request merged**
