### PR TITLE
Feature/eraser resize

### LINKED ISSUE #18: [FEATURE] - Request for Eraser Resize Feature in Slate AI
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
Currently, the eraser tool in Slate AI has a fixed size, which can be limiting in various editing scenarios. Users may find it frustrating when they need to perform detailed edits requiring a smaller eraser size or cover larger areas with a broader stroke using a larger eraser. The lack of a resizable eraser feature hinders the customization and efficiency of the editing process.

**Describe the Solution You'd Like:**
I would like to request the addition of a resizable eraser feature in Slate AI. This feature should allow users to dynamically adjust the size of the eraser tool to better suit their editing needs. The implementation could include a user-friendly interface, such as a resizable eraser icon in the toolbar or a dedicated section for eraser settings. Users should be able to manually input the desired size or use interactive methods like drag-and-drop or a slider for quick adjustments.

**Describe Alternatives You've Considered:**
One alternative solution could be to provide preset eraser sizes that users can choose from. However, this might not offer the same level of flexibility as a resizable eraser feature, as users have varying preferences and editing requirements.

### PR DESCRIPTION
**Pull request by JavidSumra**
# Title and Issue number 

Title : Request for Eraser Resize Feature in Slate AI

Issue No. : #18 

Close #18

# Video/Screenshots:

https://github.com/sd012gfhkhhvh/Slate.AI/assets/112365664/6daf4392-a9b8-4bc1-aedc-8aa27463b79b

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have gone through the  `contributing.md` file before contributing
**Additional context (Mandatory )**
**Description:**
Now, users have the ability to customize the eraser size according to their preferences by simply hovering over the "Eraser" icon. The eraser size can be adjusted dynamically, ranging from 1 to 100, providing a more flexible and user-friendly experience.

**Changes:**
- Implemented resizable eraser functionality.
- Added a range input to adjust eraser size.
- Enhanced user interaction with the eraser icon.

**Impact:**
This feature enhances the user interface and customization options for eraser functionality, allowing users to fine-tune their experience.

***Are you contributing under any Open-source programme?***
I am Contributing Under JWOC 2024

### CODE REVIEW

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir Can You Please Add Respective `Labels` To this PR?

**Comment by sd012gfhkhhvh** [comment]
Screenshot 2024-01-22 201507

can  you shift the popup a little to the right, otherwise it blocks the radio and its difficult to select in desktop view .

The remaining code is fine. I am thinking of creating a single dropdown/slider for all of the tools, just like ms paint, it has a single dropdown for size but has different options depending upon the selected tool. It would be more convenient rather than adjusting the size every time whiling selecting the tool. If you are interested doing that I can create a hard issue. let me know your thoughts.

**Comment by AntonyJudeShaman** [comment]
@sd012gfhkhhvh 

> Screenshot 2024-01-22 201507
> 
> can you shift the popup a little to the right, otherwise it blocks the radio and its difficult to select in desktop view .
> 
> The remaining code is fine. I am thinking of creating a single dropdown/slider for all of the tools, just like ms paint, it has a single dropdown for size but has different options depending upon the selected tool. It would be more convenient rather than adjusting the size every time whiling selecting the tool. If you are interested doing that I can create a hard issue. let me know your thoughts.

can u elaborate on this pls, like what features u expect

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh
> 
> > Screenshot 2024-01-22 201507
> > can you shift the popup a little to the right, otherwise it blocks the radio and its difficult to select in desktop view .
> > The remaining code is fine. I am thinking of creating a single dropdown/slider for all of the tools, just like ms paint, it has a single dropdown for size but has different options depending upon the selected tool. It would be more convenient rather than adjusting the size every time whiling selecting the tool. If you are interested doing that I can create a hard issue. let me know your thoughts.
> 
> can u elaborate on this pls, like what features u expect

Please refer to the Microsoft paint and observe how they handle sizing. There is a single dropdown for all tools and the optons under dropdown dynamically changes depending upon the tool selected.

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra checked your PR . You did a great job, Its working fine with no conflicts. 
Kindly make pr to dev branch, you have made pr to the main branch by mistake.

**Comment by sd012gfhkhhvh** [comment]
@JavidSumra the feature I am talking about -

paint
 there is one single dropdown for selecting size for all the tool-strokes and eraser.

**Comment by JavidSumra** [comment]
Done @sd012gfhkhhvh Sir

**Comment by JavidSumra** [comment]
Hey @sd012gfhkhhvh Sir I Changed Branch.

**Comment by sd012gfhkhhvh** [comment]
issue #18 has been resolved under pr#22 and merged sucsessfully.

**Comment by AntonyJudeShaman** [comment]
> @JavidSumra the feature I am talking about -
> 
> paint there is one single dropdown for selecting size for all the tool-strokes and eraser.

i would like to work on this

**Comment by JavidSumra** [comment]
> > @JavidSumra the feature I am talking about -
> > 
> > paint there is one single dropdown for selecting size for all the tool-strokes and eraser.
> 
> i would like to work on this

Hey @AntonyJudeShaman I am Working on it already 😀

**Pull request merged**
