### PR TITLE
Updated Landing page UI and fixed UI in room page

### LINKED ISSUE #16: Enhancing the UI of the landing page and fixing UI in room page
- [x]  I agree to follow this project's Contributing Guidelines.

# UI enhancement of landing page
## The current landing page does not match the theme colors of the site like in the join room.
Screenshot 2024-01-18 065646

**Describe the Solution You'd Like:**
I am proposing a rebuild of the UI for the current landing page based on the theme colors of the site. We already have the color schemes finalized which have been used in the Join Room Page also.
image

After the Update, the UI will be responsive and it will match the color scheme of the site

# Fixing the UI on the room page
## Some issues with the UI on the room page need to be fixed

1. The tools section is taking too much space than required which needs to be fixed and the canvas should acquire more space.
2.  Apart from that the chat popup box should not have a scrollbar
Screenshot 2024-01-18 233329

### PR DESCRIPTION
**Pull request by 0xMishra**
# Updated Landing page UI and fixed UI in room page #16 

Title : Enhancing the UI of the landing page and fixing UI in room page 

Issue No. : 16

Code Stack : .jsx

Close #16 

# Video/Screenshots (mandatory)

The Updated UI of landing page in desktop and mobile view
Screenshot 2024-01-19 132523
Screenshot 2024-01-19 132551

Now in the room page you can see that there is no scrollbar in the chatbox component
Screenshot 2024-01-19 133259

The canvas components have dotted borders and appropriate amount of space on the screen
Screenshot 2024-01-19 133556

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**
Updated the UI of landing page to fit the colorscheme of the site. Fixed some minor UI bugs in the room page like the width allocation for the canvas and toolbar components and the scrollbar removal in chat box component

***Are you contributing under any Open-source programme?***
Contributing under JWOC

### CODE REVIEW

**Comment by sd012gfhkhhvh** [comment]
@mishra811 the text area is still overflowing.  and in mobile view its even more horible. Try to give all the components of the chatbox a height and max-height w.r.t the parent div(you can use % instade of px or rem.) And keep the send button just right to the text area.

**Comment by 0xMishra** [comment]
It was working fine locally when I changed it. Let me look into it

**Comment by 0xMishra** [comment]
Is it ok now ?

**Comment by sd012gfhkhhvh** [comment]
> Is it ok now ?

It's looking good, I will merge after review

**Comment by sd012gfhkhhvh** [comment]
issue #16 has been resolved and merged into dev

**Pull request merged**
