### PR TITLE
fix: issue #23 and form UI improvements

### LINKED ISSUE #23: [BUG] - Room with no name and room code
- [x]  I agree to follow this project's Contributing Guidelines.

**Severity:**
-  Major

**Describe the Bug:**
A room with no name and code can be created and another user can join this empty room without entering any credentials(room code). 

**To Reproduce:**

1. Go to 'Create room page'
2. Click on 'Generate room' with name and code empty. You will be redirected to the '/' path. go back to create room page and wait.
3. Open another browser and go to create room and click generate room with all fields empty.
4. Quickly go back to the browser in step 2 to see a message that a null user has joined the room.

**Screenshots:**
image
image

**Environment (please complete the following information):**
- OS: Windows 11
- Browser: Chrome
- Version: latest

### PR DESCRIPTION
**Pull request by AntonyJudeShaman**
# Title and Issue number 
Title : https://github.com/sd012gfhkhhvh/Slate.AI/issues/23

Issue No. : 23

Close #23

# Video/Screenshots (mandatory)
image
# Checklist:

- [ ] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have gone through the  `contributing.md` file before contributing

***Are you contributing under any Open-source programme?***
Yes, JWoC

### CODE REVIEW

**Comment by sd012gfhkhhvh** [comment]
@AntonyJudeShaman Its still taking white spaces as an input, fix this

**Comment by AntonyJudeShaman** [comment]
@sd012gfhkhhvh validated the input fields with regular expressions

**Comment by sd012gfhkhhvh** [comment]
@AntonyJudeShaman use npm as a package manager, don't override using pnpm. It could lead to conflicts across different contributors.

**Comment by AntonyJudeShaman** [comment]
@sd012gfhkhhvh done

**Comment by sd012gfhkhhvh** [comment]
@AntonyJudeShaman before making any future pr kindly go through the contributing.md once, you suppose to make pr to the dev branch not in the main branch. This time it has no conflicts so i am merging your pr, but please follow the guide in the future.

**Comment by sd012gfhkhhvh** [comment]
issuse #23 has be resolved under pr #25, and successfullt merged into main

**Pull request merged**
