### PR TITLE
Added Loading Animation

### LINKED ISSUE #37: [FEATURE] - Add a loading animation while creating/joining a room
- [x]  I agree to follow this project's Contributing Guidelines.

**Is your feature request related to a problem? Please describe:**
The room creation/joining is almost instant as the load on the server in minimal for now. But when the load goes up or by means of any failure it will show white screen to the user which leads to bad user experience.

**Describe the Solution You'd Like:**
Add an artificial delay of max 3 seconds to show the implemented loading screen.

**Referance**
Refer to the joining animation of google meet while creating/joining a room and implement similar kind of effect.

**Additional Context:**

### PR DESCRIPTION
**Pull request by ramith-kulal**
# Title and Issue number 

Title : Add loading animation for creating and joining rooms

Issue No. : #37 

Code Stack :  React, CSS

Close #37 

### Description
I've added loading animations for both creating and joining rooms. Initially, I included an artificial loading time for testing purposes, as seen in the provided screen recordings. However, I've updated the functionality so that the loading animation only appears during actual loading processes.
# Video/Screenshots (mandatory)

https://github.com/sd012gfhkhhvh/Slate.AI/assets/142984776/a52b70fe-c449-4cec-b8d8-c9fdb991e18b

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

**Working under JWOC**

### CODE REVIEW

**Comment by ramith-kulal** [comment]
@sd012gfhkhhvh consider this kind request , Could we change the tag from "Medium" to "Hard" on the  pull request? It was a bit more challenging than expected.

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh consider this kind request , Could we change the tag from "Medium" to "Hard" on the pull request? It was a bit more challenging than expected.

kindly make pr to the dev branch.

**Comment by sd012gfhkhhvh** [comment]
> @sd012gfhkhhvh consider this kind request , Could we change the tag from "Medium" to "Hard" on the pull request? It was a bit more challenging than expected.

You have created a custom loader in raw css which might feel challenging, you could have used some external libraries for ease. But for your effort of making a custom loader I will think of upgrading the level

**Comment by ramith-kulal** [comment]
@sd012gfhkhhvh have a look

**Comment by sd012gfhkhhvh** [comment]
@ramith-kulal ping me up with your full name, githubId,college name etc on discord to keep track of contributors in phase-2

**Pull request merged**
